apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: holger-bubble-animation
  name: holger-bubble-animation
  namespace: holger-bubble-animation
spec:
  port:
    targetPort: 8080
  to:
    kind: Service
    name: holger-bubble-animation
    weight: 100
