---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: holger-bubble-animation
  name: holger-bubble-animation
  namespace: holger-bubble-animation
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: holger-bubble-animation
